import { useEffect, useState } from 'react';
import { decidirProduto, listarPendentes } from '../../services/revisaoService.js';
import './Revisao.css';

export default function Revisao() {
  const [itens, setItens] = useState([]); const [total, setTotal] = useState(0); const [categorias, setCategorias] = useState([]);
  const [busca, setBusca] = useState(''); const [categoria, setCategoria] = useState('Todos'); const [salvando, setSalvando] = useState(null); const [erro, setErro] = useState('');
  useEffect(() => { const controle = new AbortController(); const timer = setTimeout(async () => { try { const dados = await listarPendentes({ busca, categoria }, controle.signal); const fila = dados.dados || dados; setItens(Array.isArray(fila.itens) ? fila.itens : Array.isArray(fila.items) ? fila.items : []); setTotal(Number.isFinite(fila.total) ? fila.total : 0); setCategorias(Array.isArray(fila.categorias) ? fila.categorias : Array.isArray(fila.categories) ? fila.categories : []); setErro(''); } catch (falha) { if (falha.name !== 'AbortError') setErro(falha.mensagem || 'Não foi possível carregar a fila.'); } }, 180); return () => { controle.abort(); clearTimeout(timer); }; }, [busca, categoria]);
  const decidir = async (item, status) => { setSalvando(item.id); setErro(''); try { await decidirProduto({ productId: item.id, status, translatedName: item.translatedName }); setItens((atual) => atual.filter((produto) => produto.id !== item.id)); setTotal((atual) => Math.max(0, atual - 1)); } catch (falha) { setErro(falha.mensagem || 'A decisão não foi salva. Tente novamente.'); } finally { setSalvando(null); } };
  return <section className="revisao"><header className="revisao__cabecalho"><div><p className="revisao__marca">VIP IMPORTS</p><h1>Revisão interna do catálogo</h1></div><a href="/" target="_blank" rel="noreferrer">Ver catálogo publicado →</a></header><div className="revisao__resumo"><strong>{total}</strong><span> itens aguardando revisão</span><p>Confira a imagem, ajuste o nome em português e aprove apenas peças sem marcas ou logotipos protegidos.</p></div><div className="revisao__filtros"><select value={categoria} onChange={(e) => setCategoria(e.target.value)}><option>Todos</option>{categorias.map((nome) => <option key={nome}>{nome}</option>)}</select><input value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar pelo título original" /></div>{erro && <p className="revisao__erro">{erro}</p>}<div className="revisao__grade">{itens.map((item) => <article className="revisao__card" key={item.id}><img src={`/api/v1/admin/revisao/imagem?url=${encodeURIComponent(item.image)}&source=${encodeURIComponent(item.sourceUrl)}`} alt="" /><div><small>{item.category} • {item.supplier}</small><input value={item.translatedName} onChange={(e) => setItens((atual) => atual.map((produto) => produto.id === item.id ? { ...produto, translatedName: e.target.value } : produto))} aria-label="Nome em português"/><p>{item.translatedDetails}</p><details><summary>Nome original</summary><p>{item.name}</p></details><nav><a href={item.sourceUrl} target="_blank" rel="noreferrer">Ver origem ↗</a><button className="revisao__rejeitar" disabled={salvando === item.id} onClick={() => decidir(item, 'rejected')}>Rejeitar</button><button disabled={salvando === item.id} onClick={() => decidir(item, 'approved')}>Aprovar</button></nav></div></article>)}</div><p>Exibindo até 60 resultados por filtro.</p></section>;
}
